Brings back `./ctags` commands with explanations.

diff --git a/git_template/hooks/ctags b/git_template/hooks/ctags
--- a/git_template/hooks/ctags
+++ b/git_template/hooks/ctags
@@ -1,15 +1,25 @@
 #!/bin/sh
 
-# http://tbaggery.com/2011/08/08/effortless-ctags-with-git.html
-# vimrc
-if [ -f Gemfile ]
-  then
-  # set -e
-  # PATH="/usr/local/bin:$PATH"
-  # trap "rm -f .git/tags.$$" EXIT
-  # `brew --prefix`/bin/ctags --tag-relative -Rf.git/tags.$$ --exclude=tmp  --exclude=.git --exclude=log . `bundle show --paths`
-  # mv .git/tags.$$ .git/tags
-  # https://github.com/phstc/dotfiles/blob/master/bashrc#git_template_hooks_init
+# Ref: http://tbaggery.com/2011/08/08/effortless-ctags-with-git.html
 
-  `brew --prefix`/bin/ctags --tag-relative -Rf.git/tags --exclude=tmp  --exclude=.git --exclude=log . `bundle show --paths`
+# .vimrc calls this script `<leader>ct`.
+
+# See https://github.com/phstc/dotfiles/blob/master/bashrc#git_template_hooks_init
+if [ -f Gemfile ]
+then
+  # set -e causes the shell to exit if any subcommand or pipeline returns a non-zero status.
+  # http://serverfault.com/a/416097
+  set -e
+  # PATH="/usr/local/bin:$PATH"
+
+  # The trap command to catch the listed SIGNALS. If a signal is 0 or EXIT, the COMMANDS are executed when the shell exits.
+  # http://redsymbol.net/articles/bash-exit-traps/
+  # http://linux.die.net/Bash-Beginners-Guide/sect_12_02.html
+  trap "rm -f .git/tags.$$" EXIT
+
+  # $$ is the current pid, which helps if two processes kick off at the same time.
+  # http://tbaggery.com/2011/08/08/effortless-ctags-with-git.html#comment-995210438
+  `brew --prefix`/bin/ctags --tag-relative -Rf.git/tags.$$ --exclude=tmp  --exclude=.git --exclude=log . `bundle show --paths`
+
+  mv .git/tags.$$ .git/tags
 fi
